version: '3.7'

services:
  iris-integratedml:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    image: iris-integratedml:workshop
    container_name: iris-integratedml
    command: --check-caps false
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app