    // unexpire passwords for dev mode
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    zn "%SYS" 
    do $SYSTEM.OBJ.Load("/opt/irisapp/src/Workshop/Installer.cls", "ck") 
  
    // run installer: setup environment
    set sc = ##class(Workshop.Installer).Run(.vars) 
  
    zn "WORKSHOP"
    
    // install zpm apps
    zpm "install csvgen"
    
    // load source
    set sc = $SYSTEM.OBJ.LoadDir("/opt/irisapp/src", "ck", .errorlog, 1)
    

    halt